---
# tasks file for zabbixAgent

- name: zabbix repo
  yum_repository:
      name: zabbix44
      file: zabbix44
      description: zabbix44 YUM repo
      baseurl: https://mirrors.aliyun.com/zabbix/zabbix/4.4/rhel/7/x86_64/
      gpgcheck: no
      enabled: yes

- name: install zabbix-agent
  yum:
      name: zabbix-agent
      state: present

- name: push zabbix-agent config file
  template: 
      src: zabbix_agentd.conf.j2
      dest: /etc/zabbix/zabbix_agentd.conf
  notify: restart zabbix-agent daemon

- name: start zabbix-agent daemon
  service: 
      name: zabbix-agent
      state: started
      enabled: yes
